services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: integracaoaf
    ports:
      - "7777:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  redis:
    image: redis:7.0
    ports:
      - "6666:6379"
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 5s
      timeout: 5s
      retries: 5

  flask-api:
    build: ./record_api
    command: python app.py
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: integracaoaf
      MYSQL_PORT: 3306
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - app_network

  node-api:
    build: ./receive_send_api
    ports:
      - "4000:4000"
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      PYTHON_API_URL: http://flask-api:5000/python_api
      REDIS_URL: redis://redis:6379
      PHP_API_URL: http://php-api
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app_network

  php-api:
    build: ./auth_api
    ports:
      - "8080:80"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: integracaoaf
      MYSQL_PORT: 3306
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
